targets:
  $default:
    builders:
      json_serializable:
        options:
          # This makes all generated classes extend the base class
          any_map: false
          checked: true
          constructor: fromJson
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: snake
          include_if_null: true
        
      freezed:
        options:
          map: true
          when: true
          copyWith: true
          equal: true
          toString: true