# Configuration for Development
server:
  port: 8080
  publicHost: localhost
  publicPort: 8080
  publicScheme: http

database:
  host: database
  port: 5432
  name: calendar_dev
  username: postgres
  password: example
